import type { Lesson } from "./learning-materials";

const grammar = { title: "British Council · Ngữ pháp A1–A2", url: "https://learnenglish.britishcouncil.org/free-resources/grammar/a1-a2" };
const sounds = { title: "British Council · Sounds Right", url: "https://learnenglish.britishcouncil.org/apps/learnenglish-sounds-right" };

// Explanations and examples written for this app; links are further reading.
export const EXTRA_LESSONS: Lesson[] = [
  { id: "grammar-be", category: "Ngữ pháp", title: "Bắt đầu với am, is, are", minutes: 4,
    intro: "Dùng be để nói bạn là ai, đang ở đâu hoặc cảm thấy thế nào.",
    notes: ["I am; he/she/it is; you/we/they are. Không bỏ be trước tính từ: I am tired.", "Phủ định: thêm not sau be. Câu hỏi: đưa be lên trước chủ ngữ: Are you ready?", "Động từ thường không cần be trong hiện tại đơn: I work here, không phải I am work here."],
    samples: [{ text: "I am ready to learn.", note: "Tôi sẵn sàng học." }, { text: "She is not at home.", note: "Cô ấy không ở nhà." }, { text: "Are you tired?", note: "Bạn có mệt không?" }],
    exercise: "Điền từ: My friends ___ busy today.", choices: ["am", "is", "are"], answer: "are", explanation: "My friends là số nhiều nên dùng are.", source: grammar },
  { id: "grammar-articles", category: "Ngữ pháp", title: "a, an, the: giới thiệu và xác định", minutes: 5,
    intro: "Đừng dịch từng mạo từ. Hãy hỏi người nghe đã biết bạn nói đến vật nào chưa.",
    notes: ["a/an thường dùng với danh từ đếm được số ít khi chưa xác định: a book, an apple.", "Chọn a/an theo âm đầu: an hour (h câm), a university (bắt đầu bằng âm /j/).", "the dùng khi vật đã được xác định trong ngữ cảnh: I bought a book. The book is interesting. Không thêm a/an trước water khi nói nước nói chung."],
    samples: [{ text: "I need an umbrella.", note: "Một chiếc ô chưa xác định." }, { text: "The umbrella near the door is mine.", note: "Chiếc ô được xác định bởi vị trí." }],
    exercise: "Điền từ: We have ___ hour before lunch.", choices: ["a", "an"], answer: "an", explanation: "hour bắt đầu bằng nguyên âm vì h không được phát âm.", source: grammar },
  { id: "grammar-questions", category: "Ngữ pháp", title: "Đặt câu hỏi với do, does, did", minutes: 5,
    intro: "Một mẫu câu hỏi giúp bạn giao tiếp trong rất nhiều tình huống.",
    notes: ["Hiện tại: Do you like tea? Does she like tea? Sau do/does, dùng động từ nguyên mẫu.", "Quá khứ: Did you finish the task? Sau did không dùng finished.", "Với be và động từ khuyết thiếu, đảo chúng trực tiếp: Are you free? Can you help? Không dùng Do you are…"],
    samples: [{ text: "What time do you start work?", note: "Bạn bắt đầu làm lúc mấy giờ?" }, { text: "Does he speak English?", note: "speak không thêm s sau does." }, { text: "Where did you go yesterday?", note: "Hỏi về quá khứ." }],
    exercise: "Chọn câu đúng.", choices: ["Does she works here?", "Does she work here?"], answer: "Does she work here?", explanation: "Sau does dùng work nguyên mẫu.", source: grammar },
  { id: "grammar-future", category: "Ngữ pháp", title: "Kế hoạch: going to và will", minutes: 5,
    intro: "Nói về điều bạn dự định làm và quyết định ngay khi đang nói.",
    notes: ["be going to + động từ thường diễn tả dự định đã có: I am going to study tonight.", "will + động từ có thể diễn tả quyết định ngay lúc nói, lời hứa hoặc dự đoán: I'll help you.", "Có những ngữ cảnh dùng được cả hai. Luyện từ tình huống cụ thể thay vì coi đây là quy tắc tuyệt đối."],
    samples: [{ text: "I am going to practise after dinner.", note: "Kế hoạch đã có." }, { text: "You look busy. I will help you.", note: "Quyết định giúp ngay lúc nói." }],
    exercise: "Bạn đã lên kế hoạch học tối nay. Chọn mẫu phù hợp nhất.", choices: ["I am going to study tonight.", "I studied last night."], answer: "I am going to study tonight.", explanation: "going to phù hợp với kế hoạch tương lai đã có.", source: grammar },
  { id: "grammar-countable", category: "Ngữ pháp", title: "much, many, some, any", minutes: 5,
    intro: "Phân biệt thứ đếm được và không đếm được khi mua sắm hoặc nói về thời gian.",
    notes: ["many + danh từ đếm được số nhiều: many books. much + danh từ không đếm được: much time.", "some thường dùng trong khẳng định; any thường dùng trong phủ định/câu hỏi. Lời mời có thể dùng some: Would you like some tea?", "advice và information thường không đếm được: some advice, a piece of information; không dùng an advice."],
    samples: [{ text: "How much time do we have?", note: "time không đếm được trong nghĩa này." }, { text: "How many lessons did you finish?", note: "lessons đếm được." }, { text: "I do not have any questions.", note: "Phủ định với any." }],
    exercise: "Điền từ: How ___ books are on your desk?", choices: ["much", "many"], answer: "many", explanation: "books là danh từ đếm được số nhiều.", source: grammar },
  { id: "grammar-prepositions", category: "Ngữ pháp", title: "in, on, at cho thời gian", minutes: 4,
    intro: "Dùng ba mẫu này để kể lịch học, lịch làm việc và ngày hẹn.",
    notes: ["at + giờ: at seven; at night. on + ngày/ngày tháng: on Monday, on 5 May.", "in + tháng/năm/buổi: in October, in 2026, in the morning.", "Không thêm in/on/at trước every, last, next trong các cụm thông dụng: every day, next Monday."],
    samples: [{ text: "I study at eight in the evening.", note: "at + giờ; in + buổi." }, { text: "We meet on Friday.", note: "on + ngày trong tuần." }],
    exercise: "Điền từ: My course starts ___ October.", choices: ["in", "on", "at"], answer: "in", explanation: "Trước tên tháng dùng in.", source: grammar },
  { id: "grammar-comparison", category: "Ngữ pháp", title: "So sánh: easier, better, more useful", minutes: 5,
    intro: "So sánh hai cách học hoặc hai lựa chọn bằng một câu ngắn.",
    notes: ["Nhiều tính từ ngắn thêm -er + than: faster than. Đuôi phụ âm + y thường đổi thành -ier: easier.", "Nhiều tính từ dài dùng more: more useful than. Không dùng more easier.", "Một số dạng bất quy tắc: good → better, bad → worse. Nhất thường dùng the: the best option."],
    samples: [{ text: "This lesson is easier than the last one.", note: "Bài này dễ hơn bài trước." }, { text: "Daily practice is more useful than one long session.", note: "Câu so sánh với more useful." }],
    exercise: "Điền từ: This book is ___ than that one. (good)", choices: ["gooder", "better", "more good"], answer: "better", explanation: "Dạng so sánh hơn của good là better.", source: grammar },
  { id: "grammar-modals", category: "Ngữ pháp", title: "can, should, must: khả năng và lời khuyên", minutes: 5,
    intro: "Đề nghị giúp đỡ, nói điều bạn có thể làm và khuyên người khác.",
    notes: ["can + động từ nguyên mẫu diễn tả khả năng hoặc sự cho phép: I can swim.", "should thường dùng để khuyên: You should rest. must diễn tả nghĩa vụ mạnh hoặc sự cần thiết.", "Không thêm to hoặc -s sau các từ này. mustn't là không được phép; don't have to là không bắt buộc."],
    samples: [{ text: "Can you say that again?", note: "Đề nghị lặp lại." }, { text: "You should take a short break.", note: "Lời khuyên." }, { text: "You do not have to finish today.", note: "Không bắt buộc hoàn thành hôm nay." }],
    exercise: "You mustn't park here nghĩa là gì?", choices: ["Bạn không cần đỗ xe ở đây", "Bạn không được đỗ xe ở đây"], answer: "Bạn không được đỗ xe ở đây", explanation: "mustn't thể hiện sự cấm đoán.", source: grammar },
  { id: "pronunciation-s", category: "Phát âm", title: "Đuôi -s/-es: /s/, /z/, /ɪz/", minutes: 5,
    intro: "Luyện âm cuối khi nói danh từ số nhiều và động từ với he/she/it.",
    notes: ["Sau /p, t, k, f, θ/, đuôi thường là /s/: cups, books.", "Sau /s, z, ʃ, ʒ, tʃ, dʒ/, thường thêm âm tiết /ɪz/: buses, watches.", "Sau các âm còn lại, thường là /z/: plays, dogs. Xét âm cuối, không chỉ chữ viết. Một số từ có thay đổi đặc biệt như house → houses."],
    samples: [{ text: "books", note: "Đuôi /s/." }, { text: "dogs", note: "Đuôi /z/." }, { text: "watches", note: "Đuôi /ɪz/." }],
    exercise: "Từ nào thường có thêm một âm tiết ở đuôi số nhiều?", choices: ["books", "dogs", "buses"], answer: "buses", explanation: "bus kết thúc bằng /s/, nên buses có đuôi /ɪz/.", source: sounds },
  { id: "pronunciation-schwa", category: "Phát âm", title: "Âm /ə/: nhẹ ở âm tiết không nhấn", minutes: 4,
    intro: "Schwa giúp bạn nhận ra vì sao lời nói tự nhiên khác cách đọc từng chữ.",
    notes: ["/ə/ là nguyên âm thường gặp ở âm tiết không nhấn, như âm đầu của about.", "Giữ miệng và lưỡi thả lỏng; âm ngắn, nhẹ. Không biến mọi nguyên âm không nhấn thành /ə/ một cách máy móc.", "Nghe cả từ và giữ trọng âm chính rõ. Giọng tổng hợp chỉ là mẫu hỗ trợ; tra nguồn âm từ điển khi cần."],
    samples: [{ text: "about", note: "/əˈbaʊt/ · nhẹ âm đầu." }, { text: "banana", note: "/bəˈnɑːnə/ trong một cách đọc Anh phổ biến." }],
    exercise: "Âm nào được nhấn chính trong about?", choices: ["Âm đầu /ə/", "Âm thứ hai /baʊt/"], answer: "Âm thứ hai /baʊt/", explanation: "Dấu ˈ trong /əˈbaʊt/ đứng trước âm tiết thứ hai.", source: sounds },
  { id: "pronunciation-v-f", category: "Phát âm", title: "Phân biệt /f/ và /v/", minutes: 4,
    intro: "Hai âm có vị trí miệng gần nhau nhưng khác độ rung dây thanh.",
    notes: ["Đặt răng trên nhẹ lên môi dưới, cho hơi đi qua. Đừng khép hai môi như khi đọc /b/.", "/f/ vô thanh; /v/ hữu thanh. Đặt tay lên cổ để cảm nhận rung khi đọc /v/.", "Luyện fan–van và fine–vine; đọc chậm trước, sau đó đưa từ vào câu."],
    samples: [{ text: "fan", note: "/fæn/" }, { text: "van", note: "/væn/" }, { text: "I have five very useful videos.", note: "Luyện cả /f/ và /v/." }],
    exercise: "Âm nào làm dây thanh rung?", choices: ["/f/", "/v/"], answer: "/v/", explanation: "/v/ là âm hữu thanh; /f/ là âm vô thanh.", source: sounds },
  { id: "pronunciation-rhythm", category: "Phát âm", title: "Nhịp câu và ngữ điệu", minutes: 5,
    intro: "Đọc theo cụm ý và làm rõ từ quan trọng thay vì nhấn mọi chữ như nhau.",
    notes: ["Danh từ, động từ chính, tính từ thường nổi bật hơn; từ chức năng có thể được đọc nhẹ tùy ý người nói.", "Ngữ điệu thay đổi theo ý định. Câu hỏi yes/no có thể lên giọng, nhưng không phải câu hỏi nào cũng lên ở cuối.", "Nghe một câu ngắn, chia cụm, đọc lại rồi tự đổi một chi tiết. Ưu tiên dễ hiểu trước tốc độ."],
    samples: [{ text: "I would like a cup of tea.", note: "Thử làm nổi bật cup và tea." }, { text: "Where do you work?", note: "Nghe nhịp câu hỏi mở." }, { text: "Do you work here?", note: "So sánh ngữ điệu với câu trước." }],
    exercise: "Mục tiêu tốt khi luyện nhịp câu là gì?", choices: ["Đọc rõ cụm ý và từ quan trọng", "Nhấn mạnh mọi chữ như nhau"], answer: "Đọc rõ cụm ý và từ quan trọng", explanation: "Nhịp và cụm ý hỗ trợ người nghe hiểu thông điệp.", source: sounds },
];
