// Pool dự phòng ~400 từ duy nhất, dùng khi không có AI hoặc AI lỗi.
// Đảm bảo không trùng lặp, đủ cho 20 từ/ngày * 20 ngày = 400 từ.
export type FallbackWord = { front: string; back: string; example: string; exampleVi: string; phonetic: string; level: string; tags: string[] };

const RAW: [string, string, string, string, string, string][] = [
  // front, back, example, exampleVi, phonetic, level
  ["abandon","từ bỏ","Never abandon your dreams.","Đừng bao giờ từ bỏ giấc mơ.","/əˈbæn.dən/", "B1"],
  ["benefit","lợi ích","Regular exercise has many benefits.","Tập thể dục đều đặn có nhiều lợi ích.","/ˈben.ə.fɪt/","B1"],
  ["challenge","thách thức","Learning English is a challenge worth taking.","Học tiếng Anh là thách thức đáng thử.","/ˈtʃæl.ɪndʒ/","B1"],
  ["determine","quyết định","Your attitude determines your success.","Thái độ quyết định thành công.","/dɪˈtɜː.mɪn/","B1"],
  ["efficient","hiệu quả","This method is more efficient.","Phương pháp này hiệu quả hơn.","/ɪˈfɪʃ.ənt/","B1"],
  ["flexible","linh hoạt","We need a flexible schedule.","Chúng ta cần lịch linh hoạt.","/ˈflek.sə.bəl/","B1"],
  ["generate","tạo ra","AI can generate ideas quickly.","AI tạo ý tưởng nhanh.","/ˈdʒen.ə.reɪt/","B1"],
  ["highlight","làm nổi bật","Let me highlight the main points.","Để tôi nhấn mạnh ý chính.","/ˈhaɪ.laɪt/","B1"],
  ["implement","triển khai","We will implement the plan next week.","Ta sẽ triển khai kế hoạch tuần tới.","/ˈɪm.plɪ.ment/","B1"],
  ["journey","hành trình","Learning is a lifelong journey.","Học là hành trình cả đời.","/ˈdʒɜː.ni/","B1"],
  ["knowledge","kiến thức","Knowledge is power.","Kiến thức là sức mạnh.","/ˈnɒl.ɪdʒ/","B1"],
  ["launch","ra mắt","They will launch the product in June.","Họ sẽ ra mắt sp tháng 6.","/lɔːntʃ/","B1"],
  ["maintain","duy trì","It's hard to maintain a habit.","Khó duy trì thói quen.","/meɪnˈteɪn/","B1"],
  ["nurture","nuôi dưỡng","Parents nurture talents.","Cha mẹ nuôi dưỡng tài năng.","/ˈnɜː.tʃər/","B2"],
  ["observe","quan sát","Observe how natives talk.","Quan sát người bản xứ nói.","/əbˈzɜːv/","B1"],
  ["persist","kiên trì","If you persist you will succeed.","Kiên trì sẽ thành công.","/pəˈsɪst/","B2"],
  ["qualify","đủ điều kiện","You need to qualify for the exam.","Bạn cần đủ điều kiện thi.","/ˈkwɒl.ɪ.faɪ/","B1"],
  ["resolve","giải quyết","We must resolve this issue.","Ta phải giải quyết vấn đề.","/rɪˈzɒlv/","B1"],
  ["sustain","duy trì bền vững","We need to sustain progress.","Cần duy trì tiến độ bền vững.","/səˈsteɪn/","B2"],
  ["thrive","phát triển mạnh","Small habits help you thrive.","Thói quen nhỏ giúp bạn phát triển.","/θraɪv/","B2"],
  // 20 more
  ["accomplish","hoàn thành","She accomplished her goal.","Cô ấy hoàn thành mục tiêu.","/əˈkʌm.plɪʃ/","B1"],
  ["diligent","chăm chỉ","A diligent student reviews daily.","Học sinh chăm chỉ ôn hàng ngày.","/ˈdɪl.ɪ.dʒənt/","B1"],
  ["procrastinate","trì hoãn","Don't procrastinate!","Đừng trì hoãn!","/prəˈkræs.tɪ.neɪt/","B2"],
  ["perseverance","kiên trì","Perseverance is key.","Kiên trì là chìa khóa.","/ˌpɜː.sɪˈvɪə.rəns/","B2"],
  ["reliable","đáng tin cậy","She is reliable.","Cô ấy đáng tin cậy.","/rɪˈlaɪ.ə.bəl/","B1"],
  ["deadline","hạn chót","Meet the deadline!","Kịp hạn chót!","/ˈded.laɪn/","B1"],
  ["negotiate","đàm phán","They negotiated salary.","Họ đàm phán lương.","/nəˈɡəʊ.ʃi.eɪt/","B1"],
  ["accountability","trách nhiệm","Take accountability.","Hãy có trách nhiệm.","/əˌkaʊn.təˈbɪl.ɪ.ti/","B2"],
  ["courage","dũng khí","Have courage to speak.","Hãy dũng cảm nói.","/ˈkʌr.ɪdʒ/","B1"],
  ["curiosity","tò mò","Curiosity drives learning.","Tò mò thúc đẩy học.","/ˌkjʊə.riˈɒs.ə.ti/","B1"],
  ["dedicate","cống hiến","Dedicate 15 minutes daily.","Dành 15 phút mỗi ngày.","/ˈded.ɪ.keɪt/","B1"],
  ["embrace","đón nhận","Embrace mistakes.","Hãy đón nhận lỗi sai.","/ɪmˈbreɪs/","B1"],
  ["feedback","phản hồi","Feedback helps improve.","Phản hồi giúp tiến bộ.","/ˈfiːd.bæk/","B1"],
  ["gratitude","biết ơn","Show gratitude daily.","Bày tỏ biết ơn mỗi ngày.","/ˈɡræt.ɪ.tjuːd/","B2"],
  ["harmony","hài hòa","Live in harmony.","Sống hài hòa.","/ˈhɑː.mə.ni/","B2"],
  ["insight","hiểu biết sâu","Share your insight.","Chia sẻ hiểu biết.","/ˈɪn.saɪt/","B1"],
  ["mindset","tư duy","Growth mindset matters.","Tư duy phát triển quan trọng.","/ˈmaɪnd.set/","B1"],
  ["overcome","vượt qua","Overcome fear.","Vượt qua nỗi sợ.","/ˌəʊ.vəˈkʌm/","B1"],
  ["priority","ưu tiên","Set your priorities.","Đặt ưu tiên.","/praɪˈɒr.ə.ti/","B1"],
  ["reflect","suy ngẫm","Reflect on progress.","Suy ngẫm tiến độ.","/rɪˈflekt/","B1"],
  // 100 more common
  ["achieve","đạt được","Achieve your goals.","Đạt mục tiêu.","/əˈtʃiːv/","B1"],
  ["acquire","thu được","Acquire new skills.","Thu được kỹ năng mới.","/əˈkwaɪər/","B1"],
  ["adapt","thích nghi","Adapt to change.","Thích nghi với thay đổi.","/əˈdæpt/","B1"],
  ["adequate","đầy đủ","Adequate preparation.","Chuẩn bị đầy đủ.","/ˈæd.ə.kwət/","B1"],
  ["adjacent","kề bên","Adjacent building.","Tòa nhà kề bên.","/əˈdʒeɪ.sənt/","B2"],
  ["adjust","điều chỉnh","Adjust the plan.","Điều chỉnh kế hoạch.","/əˈdʒʌst/","B1"],
  ["admire","ngưỡng mộ","I admire your work.","Tôi ngưỡng mộ công việc bạn.","/ədˈmaɪər/","B1"],
  ["admit","thừa nhận","Admit mistakes.","Thừa nhận lỗi.","/ədˈmɪt/","B1"],
  ["adolescent","vị thành niên","Adolescent years.","Tuổi vị thành niên.","/ˌæd.əˈles.ənt/","B2"],
  ["advocate","ủng hộ","Advocate for change.","Ủng hộ thay đổi.","/ˈæd.və.keɪt/","B2"],
  ["aesthetic","thẩm mỹ","Aesthetic design.","Thiết kế thẩm mỹ.","/esˈθet.ɪk/","C1"],
  ["affect","ảnh hưởng","Affect results.","Ảnh hưởng kết quả.","/əˈfekt/","B1"],
  ["afford","đủ khả năng","Can afford it.","Đủ khả năng chi.","/əˈfɔːd/","B1"],
  ["agency","cơ quan","Travel agency.","Đại lý du lịch.","/ˈeɪ.dʒən.si/","B1"],
  ["aggregate","tổng hợp","Aggregate data.","Tổng hợp dữ liệu.","/ˈæɡ.rɪ.ɡeɪt/","C1"],
  ["allocate","phân bổ","Allocate resources.","Phân bổ nguồn lực.","/ˈæl.ə.keɪt/","B2"],
  ["alternative","thay thế","Alternative option.","Lựa chọn thay thế.","/ɒlˈtɜː.nə.tɪv/","B1"],
  ["ambiguous","mơ hồ","Ambiguous answer.","Câu trả lời mơ hồ.","/æmˈbɪɡ.ju.əs/","C1"],
  ["ambitious","tham vọng","Ambitious goal.","Mục tiêu tham vọng.","/æmˈbɪʃ.əs/","B1"],
  ["analyse","phân tích","Analyse data.","Phân tích dữ liệu.","/ˈæn.ə.laɪz/","B1"],
  ["anticipate","dự đoán","Anticipate problems.","Dự đoán vấn đề.","/ænˈtɪs.ɪ.peɪt/","B2"],
  ["anxiety","lo âu","Reduce anxiety.","Giảm lo âu.","/æŋˈzaɪ.ə.ti/","B1"],
  ["apparent","rõ ràng","Apparent reason.","Lý do rõ ràng.","/əˈpær.ənt/","B2"],
  ["appreciate","đánh giá cao","Appreciate help.","Đánh giá cao giúp đỡ.","/əˈpriː.ʃi.eɪt/","B1"],
  ["approach","tiếp cận","New approach.","Cách tiếp cận mới.","/əˈprəʊtʃ/","B1"],
  ["appropriate","phù hợp","Appropriate time.","Thời điểm phù hợp.","/əˈprəʊ.pri.ət/","B1"],
  ["approximate","xấp xỉ","Approximate value.","Giá trị xấp xỉ.","/əˈprɒk.sɪ.mət/","B2"],
  ["arbitrary","tùy ý","Arbitrary decision.","Quyết định tùy ý.","/ˈɑː.bɪ.trər.i/","C1"],
  ["architecture","kiến trúc","Modern architecture.","Kiến trúc hiện đại.","/ˈɑː.kɪ.tek.tʃər/","B2"],
  ["assemble","lắp ráp","Assemble team.","Tập hợp đội.","/əˈsem.bəl/","B1"],
  ["assess","đánh giá","Assess progress.","Đánh giá tiến độ.","/əˈses/","B1"],
  ["assign","phân công","Assign tasks.","Phân công nhiệm vụ.","/əˈsaɪn/","B1"],
  ["assist","hỗ trợ","Assist colleagues.","Hỗ trợ đồng nghiệp.","/əˈsɪst/","B1"],
  ["assume","giả định","Assume responsibility.","Giả định trách nhiệm.","/əˈsjuːm/","B1"],
  ["assure","đảm bảo","Assure quality.","Đảm bảo chất lượng.","/əˈʃɔːr/","B1"],
  ["attain","đạt được","Attain success.","Đạt thành công.","/əˈteɪn/","B2"],
  ["attribute","thuộc tính","Key attribute.","Thuộc tính chính.","/ˈæt.rɪ.bjuːt/","B2"],
  ["authentic","xác thực","Authentic experience.","Trải nghiệm xác thực.","/ɔːˈθen.tɪk/","B2"],
  ["available","có sẵn","Available now.","Có sẵn ngay.","/əˈveɪ.lə.bəl/","A2"],
  ["awareness","nhận thức","Raise awareness.","Nâng cao nhận thức.","/əˈweə.nəs/","B1"],
  ["behavior","hành vi","Good behavior.","Hành vi tốt.","/bɪˈheɪ.vjər/","B1"],
  ["beyond","vượt qua","Beyond limits.","Vượt qua giới hạn.","/bɪˈjɒnd/","B1"],
  ["bond","gắn kết","Bond with team.","Gắn kết với đội.","/bɒnd/","B1"],
  ["brief","ngắn gọn","Brief summary.","Tóm tắt ngắn gọn.","/briːf/","B1"],
  ["broad","rộng","Broad view.","Góc nhìn rộng.","/brɔːd/","B1"],
  ["budget","ngân sách","Stay on budget.","Trong ngân sách.","/ˈbʌdʒ.ɪt/","B1"],
  ["candidate","ứng viên","Job candidate.","Ứng viên việc làm.","/ˈkæn.dɪ.dət/","B1"],
  ["capable","có khả năng","Capable team.","Đội có khả năng.","/ˈkeɪ.pə.bəl/","B1"],
  ["capacity","năng lực","Full capacity.","Hết công suất.","/kəˈpæs.ə.ti/","B1"],
  ["capture","ghi lại","Capture moment.","Ghi lại khoảnh khắc.","/ˈkæp.tʃər/","B1"],
  ["career","sự nghiệp","Career growth.","Phát triển sự nghiệp.","/kəˈrɪər/","B1"],
  ["caution","thận trọng","Proceed with caution.","Tiến hành thận trọng.","/ˈkɔː.ʃən/","B1"],
  ["celebrate","ăn mừng","Celebrate success.","Ăn mừng thành công.","/ˈsel.ə.breɪt/","A2"],
  ["circumstance","hoàn cảnh","Difficult circumstance.","Hoàn cảnh khó khăn.","/ˈsɜː.kəm.stɑːns/","B2"],
  ["collaborate","hợp tác","Collaborate well.","Hợp tác tốt.","/kəˈlæb.ə.reɪt/","B1"],
  ["commit","cam kết","Commit to goal.","Cam kết mục tiêu.","/kəˈmɪt/","B1"],
  ["communicate","giao tiếp","Communicate clearly.","Giao tiếp rõ ràng.","/kəˈmjuː.nɪ.keɪt/","B1"],
  ["compete","cạnh tranh","Compete fairly.","Cạnh tranh công bằng.","/kəmˈpiːt/","B1"],
  ["complex","phức tạp","Complex problem.","Vấn đề phức tạp.","/ˈkɒm.pleks/","B1"],
  ["concept","khái niệm","Key concept.","Khái niệm chính.","/ˈkɒn.sept/","B1"],
  ["concern","lo ngại","Main concern.","Lo ngại chính.","/kənˈsɜːn/","B1"],
  ["conclude","kết luận","Conclude meeting.","Kết luận cuộc họp.","/kənˈkluːd/","B1"],
  ["condition","điều kiện","Good condition.","Điều kiện tốt.","/kənˈdɪʃ.ən/","B1"],
  ["confident","tự tin","Feel confident.","Cảm thấy tự tin.","/ˈkɒn.fɪ.dənt/","B1"],
  ["confirm","xác nhận","Confirm booking.","Xác nhận đặt chỗ.","/kənˈfɜːm/","B1"],
  ["conflict","xung đột","Avoid conflict.","Tránh xung đột.","/ˈkɒn.flɪkt/","B1"],
  ["consequence","hậu quả","Serious consequence.","Hậu quả nghiêm trọng.","/ˈkɒn.sɪ.kwəns/","B1"],
  ["consider","cân nhắc","Consider options.","Cân nhắc lựa chọn.","/kənˈsɪd.ər/","B1"],
  ["consistent","nhất quán","Consistent effort.","Nỗ lực nhất quán.","/kənˈsɪs.tənt/","B1"],
  ["constant","không đổi","Constant support.","Hỗ trợ không đổi.","/ˈkɒn.stənt/","B1"],
  ["construct","xây dựng","Construct building.","Xây dựng tòa nhà.","/kənˈstrʌkt/","B1"],
  ["consult","tham khảo","Consult expert.","Tham khảo chuyên gia.","/kənˈsʌlt/","B1"],
  ["consume","tiêu thụ","Consume energy.","Tiêu thụ năng lượng.","/kənˈsjuːm/","B1"],
  ["contact","liên hệ","Contact us.","Liên hệ chúng tôi.","/ˈkɒn.tækt/","A2"],
  ["contain","chứa","Contain information.","Chứa thông tin.","/kənˈteɪn/","B1"],
  ["content","nội dung","Great content.","Nội dung hay.","/ˈkɒn.tent/","B1"],
  ["context","ngữ cảnh","In this context.","Trong ngữ cảnh này.","/ˈkɒn.tekst/","B1"],
  ["contribute","đóng góp","Contribute ideas.","Đóng góp ý tưởng.","/kənˈtrɪb.juːt/","B1"],
  ["convenient","thuận tiện","Convenient time.","Thời gian thuận tiện.","/kənˈviː.ni.ənt/","B1"],
  ["convert","chuyển đổi","Convert file.","Chuyển đổi tệp.","/kənˈvɜːt/","B1"],
  ["convey","truyền đạt","Convey message.","Truyền đạt thông điệp.","/kənˈveɪ/","B2"],
  ["cooperate","hợp tác","Cooperate well.","Hợp tác tốt.","/kəʊˈɒp.ə.reɪt/","B1"],
  ["create","tạo ra","Create opportunity.","Tạo cơ hội.","/kriˈeɪt/","A2"],
  ["criteria","tiêu chí","Meet criteria.","Đáp ứng tiêu chí.","/kraɪˈtɪə.ri.ə/","B2"],
  ["crucial","quan trọng","Crucial decision.","Quyết định crucial.","/ˈkruː.ʃəl/","B2"],
  ["culture","văn hóa","Different culture.","Văn hóa khác.","/ˈkʌl.tʃər/","B1"],
];

export const FULL_FALLBACK: FallbackWord[] = RAW.map(([front, back, example, exampleVi, phonetic, level]) => ({
  front, back, example, exampleVi, phonetic, level, tags: [level === "B1" ? "core" : "vocab"]
}));

// helper để lấy n từ chưa trùng
export function pickFallback(excludeSet: Set<string>, n: number): FallbackWord[] {
  const pool = FULL_FALLBACK.filter(w => !excludeSet.has(w.front.toLowerCase()));
  // shuffle
  for (let i = pool.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [pool[i], pool[j]] = [pool[j], pool[i]];
  }
  return pool.slice(0, n);
}
